import { useEffect, useState } from 'react';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import { money } from '../utils/format';
import Stat from '../components/Stat';
import RequireLogin from '../components/RequireLogin';
import { Link } from 'react-router-dom';

export default function Dashboard(){
 const {user}=useAuth(); const [regs,setRegs]=useState([]); const [profile,setProfile]=useState(null);
 useEffect(()=>{if(user){api.get('/tickets/mine').then(r=>setRegs(r.data));api.get('/users/me').then(r=>setProfile(r.data));}},[user]);
 if(!user)return <RequireLogin/>;
 const active=regs.filter(r=>r.status==='active'); const paid=regs.filter(r=>r.paymentStatus==='paid');
 const submitFeedback=async(r)=>{const rating=Number(prompt('Rating 1-5'));if(!rating)return;const comment=prompt('Optional feedback')||'';try{const {data}=await api.patch(`/tickets/${r._id}/feedback`,{rating,comment});setRegs(regs.map(x=>x._id===r._id?data:x));}catch(e){alert(e.response?.data?.message||'Could not save feedback')}};
 return <div className="container py-10"><div className="flex flex-col md:flex-row justify-between gap-4"><div><span className="badge">Attendee portal</span><h1 className="text-3xl font-black mt-2">My dashboard</h1><p className="text-gray-500">Welcome back, {profile?.name||user.name}.</p></div><Link className="btn btn-primary" to="/events">Discover events</Link></div><div className="grid md:grid-cols-4 gap-4 mt-7"><Stat title="Upcoming tickets" value={active.filter(r=>r.event&&new Date(r.event.date)>=new Date()).reduce((s,r)=>s+r.quantity,0)}/><Stat title="Tickets purchased" value={paid.reduce((s,r)=>s+r.quantity,0)}/><Stat title="Total spent" value={money(paid.reduce((s,r)=>s+r.amount,0))}/><Stat title="Registrations" value={regs.length}/></div><div className="card p-5 mt-7"><h2 className="font-black text-xl">Profile & settings</h2><p className="text-gray-500 mt-1">{user.email} · {user.role}</p><Link className="text-brand font-bold inline-block mt-3" to="/profile">Manage profile →</Link></div><h2 className="font-black text-2xl mt-10">Purchased tickets</h2><div className="mt-4 space-y-3">{regs.length===0?<div className="card p-8 text-center text-gray-500">No registrations yet. <Link className="text-brand font-bold" to="/events">Find an event</Link>.</div>:regs.map(r=><div className="card p-5 flex flex-col md:flex-row justify-between gap-4" key={r._id}><div><span className="badge">{r.status}</span><h3 className="font-bold text-lg mt-2">{r.event?.title||'Event'}</h3><p className="text-gray-500">{r.quantity} ticket(s) · {money(r.amount)} · {r.paymentStatus}</p><p className="text-sm text-gray-400">{r.event&&new Date(r.event.date).toLocaleString()}</p>{r.attended&&<p className="text-sm text-green-600 font-bold mt-2">Attendance recorded</p>}{r.feedback?.rating&&<p className="text-sm text-yellow-700 mt-2">Your rating: {r.feedback.rating}/5</p>}</div><div className="flex gap-2 h-fit">{r.status==='active'&&<button className="btn btn-danger" onClick={async()=>{await api.patch(`/tickets/${r._id}/cancel`);setRegs(regs.map(x=>x._id===r._id?{...x,status:'cancelled'}:x))}}>Cancel</button>}{r.paymentStatus==='paid'&&new Date(r.event?.date||0)<new Date()&&<button className="btn btn-secondary" onClick={()=>submitFeedback(r)}>{r.feedback?.rating?'Update feedback':'Rate event'}</button>}</div></div>)}</div></div>
}
